mod admin;
mod error_reports;
mod inventory;
mod lab;
mod orders;
mod project;
mod projects;
mod tasks;
mod templates;
mod users;
pub(crate) use helpers::{empty_body, path_segment_encode, single_field_body, url_encode};
mod helpers;
